// Language configuration with country flags
 export const languageOptions = [
    { value: 'en', label: 'English', flag: '🇺🇸' },
    { value: 'fr', label: 'French', flag: '🇫🇷' },
    { value: 'de', label: 'German', flag: '🇩🇪' },
    { value: 'es', label: 'Spanish', flag: '🇪🇸' },
    { value: 'it', label: 'Italian', flag: '🇮🇹' },
    { value: 'nl', label: 'Dutch', flag: '🇳🇱' },
    { value: 'pt', label: 'Portuguese', flag: '🇵🇹' },
    { value: 'pl', label: 'Polish', flag: '🇵🇱' },
    { value: 'tr', label: 'Turkish', flag: '🇹🇷' },
    { value: 'ja', label: 'Japanese', flag: '🇯🇵' },
    { value: 'zh-cn', label: 'Chinese (Simplified)', flag: '🇨🇳' },
    { value: 'bn', label: 'Bengali', flag: '🇧🇩' },
    { value: 'bg', label: 'Bulgarian', flag: '🇧🇬' },
    { value: 'cs', label: 'Czech', flag: '🇨🇿' },
    { value: 'da', label: 'Danish', flag: '🇩🇰' },
    { value: 'et', label: 'Estonian', flag: '🇪🇪' },
    { value: 'ga', label: 'Irish', flag: '🇮🇪' },
    { value: 'el', label: 'Greek', flag: '🇬🇷' },
    { value: 'fi', label: 'Finnish', flag: '🇫🇮' },
    { value: 'hr', label: 'Croatian', flag: '🇭🇷' },
    { value: 'hu', label: 'Hungarian', flag: '🇭🇺' },
    { value: 'lt', label: 'Lithuanian', flag: '🇱🇹' },
    { value: 'lv', label: 'Latvian', flag: '🇱🇻' },
    { value: 'mt', label: 'Maltese', flag: '🇲🇹' },
    { value: 'ro', label: 'Romanian', flag: '🇷🇴' },
    { value: 'sk', label: 'Slovak', flag: '🇸🇰' },
    { value: 'sl', label: 'Slovenian', flag: '🇸🇮' },
    { value: 'sv', label: 'Swedish', flag: '🇸🇪' },
    { value: 'uk', label: 'Ukrainian', flag: '🇺🇦' },
    { value: 'ca', label: 'Catalan', flag: '🇪🇸' },
    { value: 'fa', label: 'Persian (Farsi)', flag: '🇮🇷' },
    { value: 'be', label: 'Belarusian', flag: '🇧🇾' }
  ];
